version: '3'

networks:
  local:
    driver: bridge
volumes:
  pgdata:
    driver: local    
services:

  web:
    build:
      context: ./crm-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./crm-client:/web
      - ./crm-client/build:/app/build
    depends_on:
      - server
    networks:
      - local

  server:
    build:
      context: ./crm-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./crm-server:/server
    depends_on:
      db:
        condition: service_healthy
    networks:
      - local
    command: sh -c 'npx sequelize db:migrate && npm start'  

  db:
    image: postgres:latest
    networks:
      - local
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crm"]
      interval: 30s
      timeout: 10s
      retries: 5  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    volumes:
      - pgdata:/var/lib/postgresql/data 
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./crm-client/build:/usr/share/nginx/html
    networks:
      - local    

