name: CI

# 1 
# Controls when the workflow will run

on:
  push: 
    branches: [develop]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

# 2
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
        with:
            ref: develop

      - name: Login to Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}  
          port: 22
          script: |
            mkdir app-dev
            cd app-dev
            git clone https://github.com/${{ github.repository }}
            cd crm
            git checkout develop
            git submodule update --init
            git submodule update --remote
            git reset --hard HEAD
            git pull --force

            if [ -f .env ]; then
              rm .env
            fi
            touch .env
            echo "PORT=${{secrets.DEV_API_PORT}}" >> .env
            echo "DB_DIALECT=${{secrets.DB_DIALECT}}" >> .env
            echo "DB_HOST=${{secrets.DB_HOST}}" >> .env.dev
            echo "DB_NAME=${{secrets.DEV_DB_NAME}}" >> .env
            echo "DB_PORT=${{secrets.DB_PORT}}" >> .env
            echo "DB_PWD=${{secrets.DEV_DB_PASSWORD}}" >> .env
            echo "DB_USER=${{secrets.DEV_DB_USER}}" >> .env
            echo "NODE_ENV=${{secrets.DEV_NODE_ENV}}" >> .env
            echo "TOKEN_SECRET_KEY=${{secrets.TOKEN_SECRET_KEY}}" >> .env 
            echo "REACT_APP_API_URL=${{secrets.DEV_REACT_API_URL}}" >> .env
            echo "REACT_APP_PORT=${{secrets.DEV_REACT_APP_PORT}}" >> .env
            echo "HOST=${{secrets.DEV_HOST}}" >> .env 

            sudo docker-compose -f docker-compose-dev.yml down
            npm run install-dependencies
            sudo docker-compose -f docker-compose-dev.yml up -d --build
            echo 'Deployment sucessful'
     
      
        
        
      
      
