name: CI

# 1 
# Controls when the workflow will run

on:
  push: 
    branches: [ main ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

# 2
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Login to Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}  
          port: 22
          script: |
            mkdir app
            cd app
            git clone https://github.com/${{ github.repository }}
            cd crm
            git submodule update --init
            git pull
            npm run install-dependencies
            echo 'Deployment sucessful'
            docker-compose up --d --build
      - name: Criar .env crm-server
        run: |
          cd crm-server
          echo "PORT = 8080
          DB_DIALECT = postgres
          DB_HOST = localhost
          DB_NAME = crm
          DB_PORT = 5432
          DB_PWD = postgres
          DB_USER = postgres
          NODE_ENV = development
          TOKEN_SECRET_KEY = ahaseaseesaee" > .env    
        
      
      
